# Generated by Django 5.0 on 2023-12-08 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('delivery_address_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('delivery_address', models.TextField(null=True)),
                ('delivery_address_pincode', models.IntegerField(null=True)),
                ('address_type', models.CharField(choices=[(1, 'Primary Address'), (1, 'Secondary Address')], default=1, max_length=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
