# Generated by Django 5.0 on 2023-12-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0002_deliveryaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='user_id',
            new_name='user',
        ),
    ]
