# Generated by Django 5.0 on 2023-12-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0003_rename_user_id_deliveryaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='delivery_address_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
