# Generated by Django 5.0 on 2023-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0004_alter_deliveryaddress_delivery_address_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
