# Generated by Django 5.0 on 2023-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0005_alter_users_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='delivery_address_pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
