# Generated by Django 5.0 on 2023-12-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0012_alter_category_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
