# Generated by Django 5.0 on 2023-12-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0020_alter_users_email_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150, unique=True)),
                ('company_contact_person', models.CharField(max_length=150, null=True)),
                ('company_contact_email', models.CharField(max_length=150, null=True, unique=True)),
                ('company_contact_phone', models.CharField(max_length=150, null=True)),
                ('company_address', models.TextField(null=True)),
            ],
        ),
    ]
