# Generated by Django 5.0 on 2023-12-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0023_rename_company_contact_person_company_company_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_owner',
            new_name='company_owner_name',
        ),
    ]
