# Generated by Django 5.0 on 2023-12-24 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0024_rename_company_owner_company_company_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(null=True, upload_to='media/category_img'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='subcategory_img',
            field=models.ImageField(null=True, upload_to='media/category_img'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150, unique=True)),
                ('product_img', models.ImageField(null=True, upload_to='media/prduct_img')),
                ('product_description', models.TextField(null=True)),
                ('product_price', models.CharField(max_length=150, unique=True)),
                ('product_quantity', models.CharField(max_length=150)),
                ('product_expirydate', models.DateField()),
                ('product_prescription_status', models.IntegerField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_masters.company')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_masters.sub_category')),
            ],
        ),
    ]
