# Generated by Django 5.0 on 2023-12-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0025_alter_category_category_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('offer_code', models.CharField(max_length=150, null=True, unique=True)),
                ('offer_description', models.TextField()),
                ('offer_img', models.ImageField(null=True, upload_to='media/offer_img')),
            ],
        ),
    ]
