# Generated by Django 5.0 on 2023-12-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0029_alter_product_product_price_order_order_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount_price',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
