# Generated by Django 5.0 on 2023-12-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0030_product_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
