# Generated by Django 5.0 on 2023-12-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0031_product_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_origin',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
