# Generated by Django 5.0 on 2023-12-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0032_product_product_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_origin',
            new_name='product_madein',
        ),
    ]
