# Generated by Django 5.0 on 2023-12-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0037_cart_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart_Detail',
        ),
    ]
