# Generated by Django 5.0 on 2023-12-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0038_delete_cart_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Detail',
            fields=[
                ('cart_detail_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cart_quantity', models.CharField(default=2, max_length=150, null=True)),
                ('cart_product_price', models.CharField(max_length=150, null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_masters.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_masters.product')),
            ],
        ),
    ]
