# Generated by Django 5.0 on 2023-12-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0039_cart_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_detail',
            name='cart_quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
