# Generated by Django 5.0 on 2023-12-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0040_alter_cart_detail_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_detail',
            name='cart_product_price',
            field=models.IntegerField(null=True),
        ),
    ]
