# Generated by Django 5.0 on 2023-12-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0042_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
