# Generated by Django 5.0 on 2023-12-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0043_remove_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_detail',
            name='cart_total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
