# Generated by Django 5.0 on 2024-01-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0044_cart_detail_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
