# Generated by Django 5.0 on 2024-01-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0045_alter_users_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_rate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
