# Generated by Django 5.0 on 2024-01-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0050_alter_users_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_advantage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_disadvantage',
            field=models.TextField(blank=True),
        ),
    ]
