# Generated by Django 5.0 on 2024-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0051_alter_product_product_advantage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_rate',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
