# Generated by Django 5.0 on 2024-01-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0055_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='order_discount_price',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='shipping_price',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
