# Generated by Django 5.0 on 2024-01-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0056_order_detail_order_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='total_price',
        ),
    ]
