# Generated by Django 5.0 on 2024-01-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0057_remove_order_detail_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='order_discount_price',
        ),
        migrations.AddField(
            model_name='order',
            name='order_discount_price',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
