# Generated by Django 5.0 on 2024-01-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0058_remove_order_detail_order_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
