# Generated by Django 5.0 on 2024-01-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0059_order_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Picked by courier', 'Picked by courier'), ('On the way', 'On the way'), ('Ready for pickup', 'Ready for pickup')], default='Order confirmed', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='order_tracking_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
