# Generated by Django 5.0.1 on 2024-01-25 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0060_order_order_status_order_order_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicine_masters.order'),
            preserve_default=False,
        ),
    ]
