# Generated by Django 5.0.1 on 2024-01-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0062_remove_order_detail_shipping_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Order confirmed', max_length=100),
        ),
    ]
