# Generated by Django 5.0.1 on 2024-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0064_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_discount_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(),
        ),
    ]
