# Generated by Django 5.0.1 on 2024-01-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0065_alter_product_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Order Confirmed', max_length=100),
        ),
    ]
