# Generated by Django 5.0.1 on 2024-02-05 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0080_users_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('prescription_message', models.CharField(blank=True, max_length=150, null=True)),
                ('prescription_img', models.ImageField(blank=True, null=True, upload_to='media/prescription_img')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
