# Generated by Django 5.0.1 on 2024-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0083_alter_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='order_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
