# Generated by Django 5.0.1 on 2024-02-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0084_prescription_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='order_status',
            new_name='prescription_status',
        ),
    ]
