# Generated by Django 5.0.1 on 2024-02-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0085_rename_order_status_prescription_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
