# Generated by Django 5.0.1 on 2024-02-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0087_cart_detail_prescription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_detail',
            name='prescription_status',
            field=models.IntegerField(),
        ),
    ]
