# Generated by Django 5.0.1 on 2024-02-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0088_alter_cart_detail_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='order_detail_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_masters.order_detail'),
        ),
    ]
