# Generated by Django 5.0.1 on 2024-02-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0091_rename_order_detail_id_prescription_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_status',
            field=models.CharField(default='Pending For Approve', max_length=100),
        ),
    ]
