# Generated by Django 5.0.1 on 2024-02-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0094_alter_users_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='order_detail',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_message',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_status',
        ),
    ]
