# Generated by Django 5.0.1 on 2024-02-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0095_remove_prescription_order_detail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
