# Generated by Django 5.0.1 on 2024-02-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0098_alter_prescription_prescription_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_seen',
        ),
    ]
