# Generated by Django 5.0.1 on 2024-03-02 12:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0100_notification_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyment',
            fields=[
                ('payment_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('payment_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=150)),
                ('payment_status', models.CharField(max_length=150)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_masters.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
