# Generated by Django 5.0.1 on 2024-03-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0101_pyment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pyment',
            new_name='Payment',
        ),
    ]
