# Generated by Django 5.0.1 on 2024-03-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0104_order_email_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
