# Generated by Django 5.0.1 on 2024-03-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_masters', '0106_offer_offer_required_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
